// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CopterDirection.proto

package proto;

public final class CopterDirection {
  private CopterDirection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DirectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Direction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double forward = 1;</code>
     */
    double getForward();

    /**
     * <code>double backward = 2;</code>
     */
    double getBackward();

    /**
     * <code>double left = 3;</code>
     */
    double getLeft();

    /**
     * <code>double right = 4;</code>
     */
    double getRight();

    /**
     * <code>double rotateLeft = 5;</code>
     */
    double getRotateLeft();

    /**
     * <code>double rotateRight = 6;</code>
     */
    double getRotateRight();

    /**
     * <code>double power = 7;</code>
     */
    double getPower();

    /**
     * <code>.Direction.Correct correct = 8;</code>
     */
    int getCorrectValue();
    /**
     * <code>.Direction.Correct correct = 8;</code>
     */
    Direction.Correct getCorrect();
  }
  /**
   * Protobuf type {@code Direction}
   */
  public  static final class Direction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Direction)
      DirectionOrBuilder {
    // Use Direction.newBuilder() to construct.
    private Direction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Direction() {
      forward_ = 0D;
      backward_ = 0D;
      left_ = 0D;
      right_ = 0D;
      rotateLeft_ = 0D;
      rotateRight_ = 0D;
      power_ = 0D;
      correct_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Direction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              forward_ = input.readDouble();
              break;
            }
            case 17: {

              backward_ = input.readDouble();
              break;
            }
            case 25: {

              left_ = input.readDouble();
              break;
            }
            case 33: {

              right_ = input.readDouble();
              break;
            }
            case 41: {

              rotateLeft_ = input.readDouble();
              break;
            }
            case 49: {

              rotateRight_ = input.readDouble();
              break;
            }
            case 57: {

              power_ = input.readDouble();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              correct_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CopterDirection.internal_static_Direction_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CopterDirection.internal_static_Direction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Direction.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Direction.Correct}
     */
    public enum Correct
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>ROTATE_CW = 1;</code>
       */
      ROTATE_CW(1),
      /**
       * <code>ROTATE_CCW = 2;</code>
       */
      ROTATE_CCW(2),
      /**
       * <code>LEFT = 3;</code>
       */
      LEFT(3),
      /**
       * <code>RIGHT = 4;</code>
       */
      RIGHT(4),
      /**
       * <code>FORWARD = 5;</code>
       */
      FORWARD(5),
      /**
       * <code>BACKWARD = 6;</code>
       */
      BACKWARD(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>ROTATE_CW = 1;</code>
       */
      public static final int ROTATE_CW_VALUE = 1;
      /**
       * <code>ROTATE_CCW = 2;</code>
       */
      public static final int ROTATE_CCW_VALUE = 2;
      /**
       * <code>LEFT = 3;</code>
       */
      public static final int LEFT_VALUE = 3;
      /**
       * <code>RIGHT = 4;</code>
       */
      public static final int RIGHT_VALUE = 4;
      /**
       * <code>FORWARD = 5;</code>
       */
      public static final int FORWARD_VALUE = 5;
      /**
       * <code>BACKWARD = 6;</code>
       */
      public static final int BACKWARD_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Correct valueOf(int value) {
        return forNumber(value);
      }

      public static Correct forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return ROTATE_CW;
          case 2: return ROTATE_CCW;
          case 3: return LEFT;
          case 4: return RIGHT;
          case 5: return FORWARD;
          case 6: return BACKWARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Correct>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Correct> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Correct>() {
              public Correct findValueByNumber(int number) {
                return Correct.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Direction.getDescriptor().getEnumTypes().get(0);
      }

      private static final Correct[] VALUES = values();

      public static Correct valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Correct(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Direction.Correct)
    }

    public static final int FORWARD_FIELD_NUMBER = 1;
    private double forward_;
    /**
     * <code>double forward = 1;</code>
     */
    public double getForward() {
      return forward_;
    }

    public static final int BACKWARD_FIELD_NUMBER = 2;
    private double backward_;
    /**
     * <code>double backward = 2;</code>
     */
    public double getBackward() {
      return backward_;
    }

    public static final int LEFT_FIELD_NUMBER = 3;
    private double left_;
    /**
     * <code>double left = 3;</code>
     */
    public double getLeft() {
      return left_;
    }

    public static final int RIGHT_FIELD_NUMBER = 4;
    private double right_;
    /**
     * <code>double right = 4;</code>
     */
    public double getRight() {
      return right_;
    }

    public static final int ROTATELEFT_FIELD_NUMBER = 5;
    private double rotateLeft_;
    /**
     * <code>double rotateLeft = 5;</code>
     */
    public double getRotateLeft() {
      return rotateLeft_;
    }

    public static final int ROTATERIGHT_FIELD_NUMBER = 6;
    private double rotateRight_;
    /**
     * <code>double rotateRight = 6;</code>
     */
    public double getRotateRight() {
      return rotateRight_;
    }

    public static final int POWER_FIELD_NUMBER = 7;
    private double power_;
    /**
     * <code>double power = 7;</code>
     */
    public double getPower() {
      return power_;
    }

    public static final int CORRECT_FIELD_NUMBER = 8;
    private int correct_;
    /**
     * <code>.Direction.Correct correct = 8;</code>
     */
    public int getCorrectValue() {
      return correct_;
    }
    /**
     * <code>.Direction.Correct correct = 8;</code>
     */
    public Correct getCorrect() {
      Correct result = Correct.valueOf(correct_);
      return result == null ? Correct.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (forward_ != 0D) {
        output.writeDouble(1, forward_);
      }
      if (backward_ != 0D) {
        output.writeDouble(2, backward_);
      }
      if (left_ != 0D) {
        output.writeDouble(3, left_);
      }
      if (right_ != 0D) {
        output.writeDouble(4, right_);
      }
      if (rotateLeft_ != 0D) {
        output.writeDouble(5, rotateLeft_);
      }
      if (rotateRight_ != 0D) {
        output.writeDouble(6, rotateRight_);
      }
      if (power_ != 0D) {
        output.writeDouble(7, power_);
      }
      if (correct_ != Correct.NONE.getNumber()) {
        output.writeEnum(8, correct_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (forward_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, forward_);
      }
      if (backward_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, backward_);
      }
      if (left_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, left_);
      }
      if (right_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, right_);
      }
      if (rotateLeft_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, rotateLeft_);
      }
      if (rotateRight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, rotateRight_);
      }
      if (power_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, power_);
      }
      if (correct_ != Correct.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, correct_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Direction)) {
        return super.equals(obj);
      }
      Direction other = (Direction) obj;

      boolean result = true;
      result = result && (
          Double.doubleToLongBits(getForward())
          == Double.doubleToLongBits(
              other.getForward()));
      result = result && (
          Double.doubleToLongBits(getBackward())
          == Double.doubleToLongBits(
              other.getBackward()));
      result = result && (
          Double.doubleToLongBits(getLeft())
          == Double.doubleToLongBits(
              other.getLeft()));
      result = result && (
          Double.doubleToLongBits(getRight())
          == Double.doubleToLongBits(
              other.getRight()));
      result = result && (
          Double.doubleToLongBits(getRotateLeft())
          == Double.doubleToLongBits(
              other.getRotateLeft()));
      result = result && (
          Double.doubleToLongBits(getRotateRight())
          == Double.doubleToLongBits(
              other.getRotateRight()));
      result = result && (
          Double.doubleToLongBits(getPower())
          == Double.doubleToLongBits(
              other.getPower()));
      result = result && correct_ == other.correct_;
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FORWARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getForward()));
      hash = (37 * hash) + BACKWARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getBackward()));
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLeft()));
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRight()));
      hash = (37 * hash) + ROTATELEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRotateLeft()));
      hash = (37 * hash) + ROTATERIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRotateRight()));
      hash = (37 * hash) + POWER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getPower()));
      hash = (37 * hash) + CORRECT_FIELD_NUMBER;
      hash = (53 * hash) + correct_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Direction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Direction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Direction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Direction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Direction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Direction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Direction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Direction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Direction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Direction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Direction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Direction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Direction)
        DirectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CopterDirection.internal_static_Direction_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CopterDirection.internal_static_Direction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Direction.class, Builder.class);
      }

      // Construct using proto.CopterDirection.Direction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        forward_ = 0D;

        backward_ = 0D;

        left_ = 0D;

        right_ = 0D;

        rotateLeft_ = 0D;

        rotateRight_ = 0D;

        power_ = 0D;

        correct_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CopterDirection.internal_static_Direction_descriptor;
      }

      public Direction getDefaultInstanceForType() {
        return Direction.getDefaultInstance();
      }

      public Direction build() {
        Direction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Direction buildPartial() {
        Direction result = new Direction(this);
        result.forward_ = forward_;
        result.backward_ = backward_;
        result.left_ = left_;
        result.right_ = right_;
        result.rotateLeft_ = rotateLeft_;
        result.rotateRight_ = rotateRight_;
        result.power_ = power_;
        result.correct_ = correct_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Direction) {
          return mergeFrom((Direction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Direction other) {
        if (other == Direction.getDefaultInstance()) return this;
        if (other.getForward() != 0D) {
          setForward(other.getForward());
        }
        if (other.getBackward() != 0D) {
          setBackward(other.getBackward());
        }
        if (other.getLeft() != 0D) {
          setLeft(other.getLeft());
        }
        if (other.getRight() != 0D) {
          setRight(other.getRight());
        }
        if (other.getRotateLeft() != 0D) {
          setRotateLeft(other.getRotateLeft());
        }
        if (other.getRotateRight() != 0D) {
          setRotateRight(other.getRotateRight());
        }
        if (other.getPower() != 0D) {
          setPower(other.getPower());
        }
        if (other.correct_ != 0) {
          setCorrectValue(other.getCorrectValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Direction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Direction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double forward_ ;
      /**
       * <code>double forward = 1;</code>
       */
      public double getForward() {
        return forward_;
      }
      /**
       * <code>double forward = 1;</code>
       */
      public Builder setForward(double value) {
        
        forward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double forward = 1;</code>
       */
      public Builder clearForward() {
        
        forward_ = 0D;
        onChanged();
        return this;
      }

      private double backward_ ;
      /**
       * <code>double backward = 2;</code>
       */
      public double getBackward() {
        return backward_;
      }
      /**
       * <code>double backward = 2;</code>
       */
      public Builder setBackward(double value) {
        
        backward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double backward = 2;</code>
       */
      public Builder clearBackward() {
        
        backward_ = 0D;
        onChanged();
        return this;
      }

      private double left_ ;
      /**
       * <code>double left = 3;</code>
       */
      public double getLeft() {
        return left_;
      }
      /**
       * <code>double left = 3;</code>
       */
      public Builder setLeft(double value) {
        
        left_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double left = 3;</code>
       */
      public Builder clearLeft() {
        
        left_ = 0D;
        onChanged();
        return this;
      }

      private double right_ ;
      /**
       * <code>double right = 4;</code>
       */
      public double getRight() {
        return right_;
      }
      /**
       * <code>double right = 4;</code>
       */
      public Builder setRight(double value) {
        
        right_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double right = 4;</code>
       */
      public Builder clearRight() {
        
        right_ = 0D;
        onChanged();
        return this;
      }

      private double rotateLeft_ ;
      /**
       * <code>double rotateLeft = 5;</code>
       */
      public double getRotateLeft() {
        return rotateLeft_;
      }
      /**
       * <code>double rotateLeft = 5;</code>
       */
      public Builder setRotateLeft(double value) {
        
        rotateLeft_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rotateLeft = 5;</code>
       */
      public Builder clearRotateLeft() {
        
        rotateLeft_ = 0D;
        onChanged();
        return this;
      }

      private double rotateRight_ ;
      /**
       * <code>double rotateRight = 6;</code>
       */
      public double getRotateRight() {
        return rotateRight_;
      }
      /**
       * <code>double rotateRight = 6;</code>
       */
      public Builder setRotateRight(double value) {
        
        rotateRight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rotateRight = 6;</code>
       */
      public Builder clearRotateRight() {
        
        rotateRight_ = 0D;
        onChanged();
        return this;
      }

      private double power_ ;
      /**
       * <code>double power = 7;</code>
       */
      public double getPower() {
        return power_;
      }
      /**
       * <code>double power = 7;</code>
       */
      public Builder setPower(double value) {
        
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double power = 7;</code>
       */
      public Builder clearPower() {
        
        power_ = 0D;
        onChanged();
        return this;
      }

      private int correct_ = 0;
      /**
       * <code>.Direction.Correct correct = 8;</code>
       */
      public int getCorrectValue() {
        return correct_;
      }
      /**
       * <code>.Direction.Correct correct = 8;</code>
       */
      public Builder setCorrectValue(int value) {
        correct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Direction.Correct correct = 8;</code>
       */
      public Correct getCorrect() {
        Correct result = Correct.valueOf(correct_);
        return result == null ? Correct.UNRECOGNIZED : result;
      }
      /**
       * <code>.Direction.Correct correct = 8;</code>
       */
      public Builder setCorrect(Correct value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        correct_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Direction.Correct correct = 8;</code>
       */
      public Builder clearCorrect() {
        
        correct_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Direction)
    }

    // @@protoc_insertion_point(class_scope:Direction)
    private static final Direction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Direction();
    }

    public static Direction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Direction>
        PARSER = new com.google.protobuf.AbstractParser<Direction>() {
      public Direction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Direction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Direction> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Direction> getParserForType() {
      return PARSER;
    }

    public Direction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Direction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Direction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025CopterDirection.proto\"\214\002\n\tDirection\022\017\n" +
      "\007forward\030\001 \001(\001\022\020\n\010backward\030\002 \001(\001\022\014\n\004left" +
      "\030\003 \001(\001\022\r\n\005right\030\004 \001(\001\022\022\n\nrotateLeft\030\005 \001(" +
      "\001\022\023\n\013rotateRight\030\006 \001(\001\022\r\n\005power\030\007 \001(\001\022#\n" +
      "\007correct\030\010 \001(\0162\022.Direction.Correct\"b\n\007Co" +
      "rrect\022\010\n\004NONE\020\000\022\r\n\tROTATE_CW\020\001\022\016\n\nROTATE" +
      "_CCW\020\002\022\010\n\004LEFT\020\003\022\t\n\005RIGHT\020\004\022\013\n\007FORWARD\020\005" +
      "\022\014\n\010BACKWARD\020\006B\030\n\005protoB\017CopterDirection" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Direction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Direction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Direction_descriptor,
        new String[] { "Forward", "Backward", "Left", "Right", "RotateLeft", "RotateRight", "Power", "Correct", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
